[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "edit-training"
version = "2023.08"
description = "Machine Learning Training with EDIT"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["edit"]
authors = [
  {email = "harrison.cook@bom.gov.au"},
  {name = "Harrison Cook"}
]
maintainers = [
  {name = "Harrison Cook", email = "harrison.cook@bom.gov.au"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "edit.pipeline",
    "einops", 
    "scikit-learn", 
    "scipy", 
]

[project.optional-dependencies]
pytorch = [
  "pytorch-lightning",
  "tensorboard",
  "onnx",
  "torch", 
  "piqa",
]
xgboost = [
  "xgboost",
  "scikit-learn",
]
all = [
  "edit.training[pytorch]",
  "edit.training[xgboost]",

]


[project.urls]
homepage = "https://bom.gov.au"
documentation = "https://git.nci.org.au/bom/dset/edit-package/documentation"
repository = "https://git.nci.org.au/bom/dset/edit-package/training"

[project.scripts]
edit-training = "edit.training.commands:entry_point"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true

[tool.setuptools.packages.find]
where = ["src"] 
