[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "edit-tutorial"
description = "Tutorials for EDIT"
requires-python = ">=3.9"
keywords = ["edit"]
authors = [
  {email = "tennessee.leeuwenburg@bom.gov.au"},
  {name = "Tennessee Leeuwenburg"}
]
maintainers = [
  {name = "Tennessee Leeuwenburg", email = "tennessee.leeuwenburg@bom.gov.au"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "edit.data>=1.0.0",
  "edit.pipeline",
  "edit.training",
  "rich",
  "ipywidgets",
  "scores",
  "dask==2024.9.1",
  "jupyterlab",
  "ipykernel"
]
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[project.urls]
homepage = "http://bom.gov.au"
documentation = "https://git.nci.org.au/bom/dset/edit-package/archives/NCI"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[tool.hatch.version]
path = "src/edit/tutorial/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/edit/"]
