site_name: "NCI Indexes"

theme:
  name: "material"
  highlightjs: true
  hljs_languages:
      - python
      - yaml
      - shell
  navigation_depth: 4
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt 
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - content.code.select
  - content.code.copy
  - content.code.annotate 

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: aqua
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
# - coverage
- search
- autorefs
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index

- mkdocstrings:
    default_handler: python
    handlers:
      python:
        docstring_style: "google"
        paths: [src]
        members_order: source
        show_submodules: True
        options:
          allow_inspection: false
          show_source: false
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
nav:
- Home: index.md
# defer to gen-files + literate-nav
- Reference: reference/

extra_css:
  - css/code_select.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

repo_url: https://git.nci.org.au/bom/dset/edit-package/archives/nci

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra:
  version:
    provider: mike