[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyearthtools-pipeline"
description = "Data Pipelines with pyearthtools"
requires-python = ">=3.9"
keywords = ["pyearthtools"]
authors = [
  {email = "harrison.cook@bom.gov.au"},
  {name = "Harrison Cook"}
]
maintainers = [
  {name = "Harrison Cook", email = "harrison.cook@bom.gov.au"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyearthtools-utils>=1.1.0",
    "pyearthtools-data>=1.0.0",
    "xarray",
    "pandas",
    "graphviz",
    "einops",
]


dynamic = ["version", "readme"]

[project.optional-dependencies]
distributed = [
  "dask",
  "distributed",
]
remapping = [
  "healpy","reproject",
]
all = [
  "pyearthtools-pipeline[distributed, remapping]",
  "pyearthtools-data[all]",
]

[project.urls]
homepage = "https://bom.gov.au"
documentation = "https://git.nci.org.au/bom/dset/pyearthtools-package/documentation"
repository = "https://git.nci.org.au/bom/dset/pyearthtools-package/pipeline_v2"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true

[tool.setuptools.packages.find]
include = ["pyearthtools.pipeline"]
where = ["src/"]

[tool.setuptools_scm]
version_file = "src/pyearthtools/pipeline/_version.py"

[tool.ruff.lint]
ignore-init-module-imports = false

[tool.hatch.version]
path = "src/pyearthtools/pipeline/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/pyearthtools/"]