[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "pyearthtools-training"
description = "Machine Learning Training with pyearthtools"
requires-python = ">=3.9"
keywords = ["pyearthtools"]
authors = [
  {email = "harrison.cook@bom.gov.au"},
  {name = "Harrison Cook"}
]
maintainers = [
  {name = "Harrison Cook", email = "harrison.cook@bom.gov.au"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyearthtools-pipeline",
    "pyearthtools-utils>=1.1.0",
    "einops", 
    "scikit-learn", 
    "scipy", 
]
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[project.optional-dependencies]
lightning = [
  "lightning",
  "tensorboard",
  "torch", 
  "piqa",
  "tensorly",
]
pytorch =[
  "pyearthtools.training[lightning]",
]
xgboost = [
  "xgboost",
  "scikit-learn",
]
onnx = [
  "onnx",
  "onnxruntime",
]
onnx_gpu = [
  "onnxruntime_gpu",
]
all = [
  "pyearthtools-training[lightning]",
  "pyearthtools-training[xgboost]",
  "pyearthtools-training[onnx_gpu]",
]


[project.urls]
homepage = "https://bom.gov.au"
documentation = "https://git.nci.org.au/bom/dset/pyearthtools-package/documentation"
repository = "https://git.nci.org.au/bom/dset/pyearthtools-package/training"

[project.scripts]
pyearthtools-training = "pyearthtools.training.commands:entry_point"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true

[tool.hatch.version]
path = "src/pyearthtools/training/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/pyearthtools/"]
