
image: continuumio/miniconda3:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  # - pull

# pages:
#   tags: [docker]
#   stage: pages
#   script:
#     - echo "The site will be deployed to $CI_PAGES_URL"
#   artifacts:
#     paths:
#       - site
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH




build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: [docker]
  before_script:
    - mkdir ~/.ssh/
    - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - echo "${SSH_PUSH_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  script:
    - echo "Setting up environment and installing package..."
    - conda init bash
    - source ~/.bashrc
    - conda create -n edit_environment
    - conda activate edit_environment
    - pip install -r requirements.txt
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/data.git    
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/utils.git    
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/pipeline_v2.git    
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/training.git    
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/verification.git    
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.nci.org.au/bom/dset/edit-package/models.git    
    - git clone https://gitlab-ci-token:${SSH_PUSH_KEY}@git.nci.org.au/bom/dset/edit-package/documentation.git    
    
    - pip install ./data --no-dependencies
    - pip install ./training --no-dependencies
    - pip install ./utils --no-dependencies
    - pip install ./pipeline_v2 --no-dependencies
    - pip install ./verification --no-dependencies
    - pip install ./models --no-dependencies
    - cd documentation

    - git remote add gitlab_origin https://docbuilder:$SSH_PUSH_KEY@git.nci.org.au/bom/dset/edit-package/documentation.git
    - git config user.email "ci@bom.com"
    - git config user.name "Documentation Builder"
    - mkdocs build
    - git add -f site/*
    - git commit -m "Update Docs"
    - git push gitlab_origin HEAD:docs -o ci.skip -f